controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - BJ
      - SJ
      - EJ
      - W1J
      - W2J
      - W3J
initial:  # Define initial robot poses.
  - group: arm
    pose: home